apiVersion: v1
kind: Secret
metadata:
  name: hyperviseur-secrets
type: Opaque
data:
  # REMPLACEZ CES VALEURS PAR VOS MOTS DE PASSE EN BASE64
  # echo -n "mon_password" | base64
  DB_USER: ""
  DB_PASS: ""
  POLLING_SERVICE_TOKEN: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
