apiVersion: v1
kind: Secret
metadata:
  name: hyperviseur-secrets
type: Opaque
stringData:
  # Remplissez ces valeurs avec les vrais identifiants de prod
  DB_USER: "postgres"
  DB_PASS: "CHANGE_ME_TO_REAL_PASSWORD"
  POLLING_SERVICE_TOKEN: "CHANGE_ME_TO_SECURE_TOKEN"
