{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hi2-helm.fullname" . }}-backup-pvc
  labels:
    {{- include "hi2-helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storage.size }}
  storageClassName: {{ .Values.backup.storage.className }}
{{- end }}
