apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hi2-helm.fullname" . }}-secrets
  labels:
    {{- include "hi2-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASS: {{ .Values.secrets.dbPass | quote }}
  POLLING_SERVICE_TOKEN: {{ .Values.secrets.pollingServiceToken | quote }}
  SUPERADMIN_USERNAME: {{ .Values.secrets.superadminUsername | quote }}
  SUPERADMIN_EMAIL: {{ .Values.secrets.superadminEmail | quote }}
  SUPERADMIN_PASSWORD: {{ .Values.secrets.superadminPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  AZURE_TENANT_ID: {{ .Values.secrets.azureTenantId | quote }}
  AZURE_CLIENT_ID: {{ .Values.secrets.azureClientId | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.secrets.azureClientSecret | quote }}
  AZURE_SENDER_EMAIL: {{ .Values.secrets.azureSenderEmail | quote }}
  AZURE_REDIRECT_URI: {{ .Values.secrets.azureRedirectUri | quote }}
  FRONTEND_BASE_URL: {{ .Values.secrets.frontendBaseUrl | quote }}
  SMTP_HOST: {{ .Values.secrets.smtpHost | quote }}
  SMTP_PORT: {{ .Values.secrets.smtpPort | quote }}
  SMTP_USER: {{ .Values.secrets.smtpUser | quote }}
  SMTP_PASS: {{ .Values.secrets.smtpPass | quote }}
