{{- if .Values.netclient.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: netmaker-access-token
  labels:
    {{- include "hi2-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.netclient.token | quote }}
{{- end }}
