{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hi2-helm.fullname" . }}-postgres
  labels:
    {{- include "hi2-helm.labels" . | nindent 4 }}
    app: {{ include "hi2-helm.fullname" . }}-postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "hi2-helm.selectorLabels" . | nindent 4 }}
    app: {{ include "hi2-helm.fullname" . }}-postgres
{{- end }}
